### ISSUE TITLE
potential translation issue

### ISSUE THREAD

**Issue by marcohutzsch1234** [datamesh-architecture/datamesh-architecture.com#5]
https://github.com/datamesh-architecture/datamesh-architecture.com/blob/ccd52adbc53ac1e0d6cd18c1aa392cf0c295cee1/index.html#L953

is really "stark" ment here or is there a missing translation?
[...] which is in **stark** contrast [...]

**Comment by jochenchrist** [comment]
Thx for the hint. 
Fixed it to "strong"
