### ISSUE TITLE
End of sentence is missing

### ISSUE THREAD

**Issue by efasel** [datamesh-architecture/datamesh-architecture.com#8]
Great article/site! :+1: 

I think this sentence stops midway:
https://github.com/datamesh-architecture/datamesh-architecture.com/blob/983fe1e55c084dfcb5d08acf8b5442dba5e43fea/index.html#L938

https://www.datamesh-architecture.com/#is-the-data-mesh-a-generic-solution-to-a-distributed-data-archit
![image](https://user-images.githubusercontent.com/5768844/162424667-56cc21ac-5300-42f3-9b2d-14fe431c0652.png)

**Comment by jochenchrist** [comment]
Thank you, Elmar. Fixed this FAQ.

-- jochen
